- name: apt
  hosts: slaves

  #vars_files: 
    #- slaves_become_pass

  tasks:
  - name: Install (state=present is optional)
    apt:
      name:
        #- python3-dev
        #- vim
        #- zip
        - less
      state: present
      update_cache: true
    become: true
