- name: cp
  hosts: hadoop

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: /home/hadoop/requirementsWithoutVersion
        dest: /home/hadoop/requirementsWithoutVersion
        owner: hadoop
        group: hadoop
        mode: '0644'
